export const FETCH_API_DATA = 'FETCH_API_DATA';
export const REFRESH_API_STATUS = 'REFRESH_API_STATUS';
export const CHANGE_API = 'CHANGE_API';
export const SELECTED_CHARACTERS_COUNTER = 'CHECKBOXES_COUNTER';