export const FETCH_API_DATA = 'FETCH_API_DATA';
export const REFRESH_API_STATUS = 'REFRESH_API_STATUS';
export const CHOOSE_ACTIVE_API = 'CHOOSE_ACTIVE_API';
export const SELECTED_CHARACTERS_COUNTER = 'CHECKBOXES_COUNTER';
export const CHECKED_APIS_COUNTER = 'CHECKED_APIS_COUNTER';
export const APIS_COUNTER = 'APIS_COUNTER';
export const ADD_COMPONENT = 'ADD_COMPONENT';